- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: gatewaypayment
    namespace: __NAMESPACE__
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: gatewaypayment
    template:
      metadata:
        labels:
          app: gatewaypayment
      spec:
        nodeSelector:
          kubernetes.io/os: linux
        containers:
          - name: gatewaypayment
            image: __AZURE_CONTAINER_REGISTRY__.azurecr.io/__CONTAINER_NAME__:__IMAGE_TAG__
            env:
            - name: LC_ALL
              value: en_US.UTF-8
            - name: LANG
              value: en_US.UTF-8
            - name: LANGUAGE
              value: en_US.UTF-8
            ports:
              - containerPort: 8096
            resources:
              limits:
                cpu: 1
                memory: 1000Mi
              requests:
                cpu: 750m
                memory: 800Mi
